--listener robotframework_reportportal.listener
--variable RP_UUID:"819e5c49-33cb-440d-ae47-c99690606735"
--variable RP_ENDPOINT:"https://reportportal.epam.com/api/v1"
--variable RP_LAUNCH:"maryana_piatrova_TEST_EXAMPLE"
--variable RP_PROJECT:"maryana_piatrova_personal"